---
- name: Instal Grafana
  hosts: all
  become: yes  # This is required to gain sudo privileges

  vars_files:
    - vars/vars.yml
    - vault/api_key.yml

  handlers:
    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: restart grafana
      ansible.builtin.systemd:
        name: grafana-server
        state: restarted
        enabled: true  # This ensures the service is enabled to start at boot    

  tasks:
    - name: Download Grafana GPG key
      ansible.builtin.get_url:
        url: https://rpm.grafana.com/gpg.key
        dest: /tmp/gpg.key
        mode: '0644'

    - name: Import GPG key
      ansible.builtin.rpm_key:
        state: present
        key: /tmp/gpg.key
      notify: reload systemd

    - name: Copy Grafana repo file
      ansible.builtin.copy:
        src: grafana.repo # Update this path to where you stored the file
        dest: /etc/yum.repos.d/grafana.repo
        mode: '0644'

    - name: Install Grafana Enterprise
      ansible.builtin.dnf:
        name: grafana-enterprise
        state: present
      notify: restart grafana

    - name: Ensure Grafana is started and enabled
      ansible.builtin.systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Ensure firewalld is stopped (since this is a test server).
      service: name=firewalld state=stopped

    - name: Install policycoreutils-python-utils for audit2allow
      ansible.builtin.dnf:
        name: policycoreutils-python-utils
        state: present  
    # this should probably be removed in production. I need the module on the test instance to help understand how to 
    # create the SELinux custom policy module that will allow the systemd unit to start. 
- import_playbook: tasks/prometheus-setup.yml

    
  

# this needs to be changed to create a service file for prometheus and then start/enable it. 
    # - name: Start Prometheus service
    #   ansible.builtin.shell:
    #     cmd: "./prometheus --config.file=./prometheus.yml"
    #     chdir: "{{ prometheus_dir.files[0].path }}"
        

# need to add task to actually start the 
# prometheus service:  " ./prometheus --config.file=./prometheus.yml"